apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    app: web-app-express
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app-express
  template:
    metadata:
      labels:
        app: web-app-express
    spec:
      containers:
      - name: web-app-express
        image: rcventura/web_app-express:v1.0.0
        ports: 
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-nodeport
spec:
  selector:
    app: web-app-express
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
