
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/focal64"

  config.vm.network "public_network"

  
   config.vm.provider "virtualbox" do |vb|
  
      #vb.name = "vagrant-linux-server"  
      vb.memory = "1024"
    end
  
    config.vm.provision "shell", path: "../scripts/identity-access-managment.sh"

    config.vm.provision "shell", path: "../scripts/apache-server.sh"

end
